FROM ocaml/opam:debian-ocaml-5.3

USER root

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        git \
        curl \
        ca-certificates \
        python3 \
        python3-pip \
        python3-venv \
        m4 \
        make \
        gcc \
        pkg-config \
        libev-dev \
        libgmp-dev \
        libssl-dev && \
    rm -rf /var/lib/apt/lists/*

USER opam
WORKDIR /workspaces/yoda
