type some = {path: string; methods: string}

(* TODO: add response codes *)

(* read file from stdin *)
let file =
  let path =
    if Array.length Sys.argv > 1 then Sys.argv.(1)
    else (
      print_string "Enter path to OpenAPI schema: " ;
      flush stdout ;
      read_line () )
  in
  In_channel.input_all (open_in path)

let initial acc =
  "(*Generated by generator.ml*)\n\n\
   open Lwt.Infix\n\n\
  \  \n\
   let icon_handler _ =\n\
  \  Lwt_io.(with_file ~mode:Input \"./static/resources/ocaml-icon.ico\" \
   read)\n\
  \  >>= fun data ->\n\
  \  Dream.respond ~headers:[(\"Content-Type\", \"image/x-icon\")] data \n\
  \ \n\
  \    let login_handler next request =\n\
  \  match Dream.session_field request \"user\" with\n\
  \  | Some _ -> next request\n\
  \  | None ->\n\
  \      Dream.json ~code:401 ~headers:[(\"Content-Type\", \
   \"application/json\")]\n\
  \        \"Unauthorized access\"\n\
  \  " ^ acc
  ^ "\n\
    \ let () = \n\
    \  let app = \n\
    \  Dream.router [\n\
    \ \tDream.get\n\
    \   \"/resources/ocaml-icon.ico\" icon_handler ;\n\
    \ \tDream.get \"/\" (fun _request\n\
    \   -> Dream.html \"/\")"

let final =
  "]\n\
  \ |> Dream.memory_sessions ~lifetime:(60.0 *. 60.0) \n\
  \ |> Dream.logger \n\
  \   in \n\
  \ Dream.run ~interface:\"0.0.0.0\" ~port:8001 app"

(* read routes from openapi file *)
let readRoutes =
  match Yaml.of_string file with
  | Error (`Msg e) -> failwith e
  | Ok (`O fields) -> (
    match List.assoc "paths" fields with
    | `O path_entries ->
        List.fold_left
          (fun acc (k, v) ->
            match v with
            | `O method_entries ->
                List.fold_left
                  (fun acc (k', _v') ->
                    match k' with
                    | "get" | "post" | "put" | "delete" ->
                        {path= k; methods= k'} :: acc
                    | _ -> acc )
                  acc method_entries
            | _ -> [] )
          [] path_entries
    | _ -> [] )
  | _ -> []

(* remove '{' & '}' *)
let subs s =
  String.map (fun c -> if c = '{' then ':' else c) s
  |> String.split_on_char '}' |> String.concat ""

(* remove "duplicates" example: removeKey "/users/:id" "users" -> "/:id"*)
let removeKey s k =
  String.sub s
    (String.length ("/" ^ k))
    (String.length s - (String.length k + 1))

(* capitalize handler of function example: /user/{id} -> userId*)
let subs2 s =
  let s' =
    String.split_on_char '{' s
    |> String.concat "" |> String.split_on_char '}' |> String.concat ""
  in
  let _, res =
    String.fold_left
      (fun (cont, acc) c ->
        if c = '/' then (cont + 1, acc)
        else if cont = 1 then
          (cont - 1, acc ^ String.make 1 (Char.uppercase_ascii c))
        else (cont, acc ^ String.make 1 c) )
      (0, "") s'
  in
  res

(* capitalize 1st char of string*)
let subs3 s =
  let s' = String.split_on_char '/' s in
  List.hd (List.tl s') |> String.capitalize_ascii

(* create string with routes *)
let rec go acc lst = function
  | [] -> (acc, lst)
  | (key, routes) :: tl ->
      (* add all routes to a scope belonging to key *)
      let dream_routes, handlers =
        List.fold_left
          (fun (acc', lst') x ->
            let dream_path = removeKey (subs x.path) key in
            let handler = x.methods ^ subs2 x.path in
            let key2 =
              Printf.sprintf "\n Dream.%s \"%s\" %s;" x.methods dream_path
                (subs3 (subs x.path) ^ String.make 1 '.' ^ handler)
            in
            (acc' ^ key2, lst' @ [handler]) )
          ("", lst) routes
      in
      let scope =
        if key = "auth" then
          Printf.sprintf "\n;Dream.scope \"/%s\" [] \n[%s\n]" key
            dream_routes
        else
          Printf.sprintf "\n;Dream.scope \"/%s\" [login_handler] \n[%s\n]"
            key dream_routes
      in
      go (acc ^ scope) handlers tl

(* get scope of route example /users/id -> users *)
let separate s = List.nth (String.split_on_char '/' s) 1

(* add route to list of routes in a pair of (key,[routes]) *)
let addRoutes key new_item lst =
  List.map
    (fun (k, items) -> if k = key then (k, new_item :: items) else (k, items))
    lst

(* group path in a list of pairs [("path",["/path/{id}"])] *)
let rec group acc = function
  | hd :: tl -> (
      let key = separate hd.path in
      match List.assoc_opt key acc with
      | Some _ -> group (addRoutes key hd acc) tl
      | None -> group ((key, [hd]) :: acc) tl )
  | [] -> acc

(* write ouput the the desired file *)
let output str _acc =
  Out_channel.with_open_text "./src/router.ml" (fun oc ->
      Out_channel.output_string oc (initial "" ^ str ^ final) )

let () =
  let a1, b2 = go "" [] (group [] readRoutes) in
  let _acc' =
    List.fold_left
      (fun acc r ->
        acc ^ Printf.sprintf "let %s _request =  \n failwith  \"%s\" \n" r r )
      "" b2
  in
  output a1 _acc'
