type some = {path: string; methods: string}

(* TODO: add response codes *)

let file = In_channel.input_all (open_in "./schemas/api.yaml")

let initial acc =
  "(*Generated by generator.ml*)\n\nopen Lwt.Infix\nopen Redis_lwt\n\nlet icon_handler _ =
  Lwt_io.(with_file ~mode:Input \"./static/resources/ocaml-icon.ico\" read)
  >>= fun data ->
  Dream.respond ~headers:[(\"Content-Type\", \"image/x-icon\")] data \n" ^ acc
^ "\n\n\ let () = \n\ \ let app = \n\ \ Dream.router [\n\ \tDream.get
   \"/resources/ocaml-icon.ico\" icon_handler ;Dream.get \"/\" (fun request
   -> Dream.html (Index.html \"ola\" \ request))" 

let final =
  "]\n\
  \ |> Dream.memory_sessions ~lifetime:(60.0 *. 60.0) \n\
  \ |> Dream.logger \n\
  \   in \n\
  \ Dream.run ~interface:\"0.0.0.0\" app"

let readRoutes =
  match Yaml.of_string file with
  | Error (`Msg e) -> failwith e
  | Ok (`O fields) -> (
    match List.assoc "paths" fields with
    | `O path_entries ->
        List.fold_left
          (fun acc (k, v) ->
            match v with
            | `O method_entries ->
                List.fold_left
                  (fun acc (k', _v') ->
                    match k' with
                    | "get" | "post" | "put" | "delete" ->
                        {path= k; methods= k'} :: acc
                    | _ -> acc )
                  acc method_entries
            | _ -> [] )
          [] path_entries
    | _ -> [] )
  | _ -> []

let subs s =
  String.map (fun c -> if c = '{' then ':' else c) s
  |> String.split_on_char '}' |> String.concat ""

let subs2 s =
  let s' =
    String.split_on_char '{' s
    |> String.concat "" |> String.split_on_char '}' |> String.concat ""
  in
  let _, res =
    String.fold_left
      (fun (cont, acc) c ->
        if c = '/' then (cont + 1, acc)
        else if cont = 1 then
          (cont - 1, acc ^ String.make 1 (Char.uppercase_ascii c))
        else (cont, acc ^ String.make 1 c) )
      (0, "") s'
  in
  res


  
let output str acc =
  Out_channel.with_open_text "./src/router.ml" (fun oc ->
      Out_channel.output_string oc (initial acc ^ str ^ final) )


let rec go acc lst = function
  | [] -> (acc, lst)
  | hd :: tl -> (
    match hd.methods with
    | "get" | "post" | "put" | "delete" ->
        let dream_path = subs hd.path in
        let handler = hd.methods ^ subs2 hd.path in
        go
          ( acc
          ^ Printf.sprintf "\n;Dream.%s \"%s\" %s" hd.methods dream_path
              handler )
          (lst @ [handler]) tl
    | e -> failwith ("\"Not Implemented\": " ^ e) )

let () =
  let acc, a = go "" [] readRoutes in
  let acc' =
    List.fold_left
      (fun acc r ->
        acc
        ^ Printf.sprintf "let %s _request =  \n failwith  \"%s\" \n" r r )
      "" a
  in
  output acc acc'
