(*Generated by parser.ml*)

open Lwt.Infix
open Redis_lwt

let getContestsIdScoreboard _request =  
 failwith NotImplemented 
let postJudgeSubmissionIdResult _request =  
 failwith NotImplemented 
let postJudgeNext _request =  
 failwith NotImplemented 
let getContestsContestIdSubmissions _request =  
 failwith NotImplemented 
let getSubmissionsId _request =  
 failwith NotImplemented 
let postSubmissions _request =  
 failwith NotImplemented 
let postProblemsIdTestcases _request =  
 failwith NotImplemented 
let getProblemsIdTestcases _request =  
 failwith NotImplemented 
let deleteProblemsId _request =  
 failwith NotImplemented 
let putProblemsId _request =  
 failwith NotImplemented 
let getProblemsId _request =  
 failwith NotImplemented 
let postContestsContestsIdProblems _request =  
 failwith NotImplemented 
let getContestsContestsIdProblems _request =  
 failwith NotImplemented 
let deleteContestsId _request =  
 failwith NotImplemented 
let putContestsId _request =  
 failwith NotImplemented 
let getContestsId _request =  
 failwith NotImplemented 
let postContests _request =  
 failwith NotImplemented 
let getContests _request =  
 failwith NotImplemented 
let postAuthRegister _request =  
 failwith NotImplemented 
let postAuthLogin _request =  
 failwith NotImplemented 
let deleteUsersId _request =  
 failwith NotImplemented 
let putUsersId _request =  
 failwith NotImplemented 
let getUsersId _request =  
 failwith NotImplemented 
let postUsers _request =  
 failwith NotImplemented 
let getUsers _request =  
 failwith NotImplemented 

;Dream.get "/contests/:id/scoreboard" getContestsIdScoreboard
;Dream.post "/judge/:submissionId/result" postJudgeSubmissionIdResult
;Dream.post "/judge/next" postJudgeNext
;Dream.get "/contests/:contestId/submissions" getContestsContestIdSubmissions
;Dream.get "/submissions/:id" getSubmissionsId
;Dream.post "/submissions" postSubmissions
;Dream.post "/problems/:id/testcases" postProblemsIdTestcases
;Dream.get "/problems/:id/testcases" getProblemsIdTestcases
;Dream.delete "/problems/:id" deleteProblemsId
;Dream.put "/problems/:id" putProblemsId
;Dream.get "/problems/:id" getProblemsId
;Dream.post "/contests/:contestsId/problems" postContestsContestsIdProblems
;Dream.get "/contests/:contestsId/problems" getContestsContestsIdProblems
;Dream.delete "/contests/:id" deleteContestsId
;Dream.put "/contests/:id" putContestsId
;Dream.get "/contests/:id" getContestsId
;Dream.post "/contests" postContests
;Dream.get "/contests" getContests
;Dream.post "/auth/register" postAuthRegister
;Dream.post "/auth/login" postAuthLogin
;Dream.delete "/users/:id" deleteUsersId
;Dream.put "/users/:id" putUsersId
;Dream.get "/users/:id" getUsersId
;Dream.post "/users" postUsers
;Dream.get "/users" getUsers