(*Generated by parser.ml*)

open Lwt.Infix
open Redis_lwt

let getContestsIdScoreboard _request =  
 failwith NotImplemented 
let postJudgeSubmissionIdResult _request =  
 failwith NotImplemented 
let postJudgeNext _request =  
 failwith NotImplemented 
let getContestsContestIdSubmissions _request =  
 failwith NotImplemented 
let getSubmissionsId _request =  
 failwith NotImplemented 
let postSubmissions _request =  
 failwith NotImplemented 
let postProblemsIdTestcases _request =  
 failwith NotImplemented 
let getProblemsIdTestcases _request =  
 failwith NotImplemented 
let deleteProblemsId _request =  
 failwith NotImplemented 
let putProblemsId _request =  
 failwith NotImplemented 
let getProblemsId _request =  
 failwith NotImplemented 
let postContestsContestsIdProblems _request =  
 failwith NotImplemented 
let getContestsContestsIdProblems _request =  
 failwith NotImplemented 
let deleteContestsId _request =  
 failwith NotImplemented 
let putContestsId _request =  
 failwith NotImplemented 
let getContestsId _request =  
 failwith NotImplemented 
let postContests _request =  
 failwith NotImplemented 
let getContests _request =  
 failwith NotImplemented 
let postAuthRegister _request =  
 failwith NotImplemented 
let postAuthLogin _request =  
 failwith NotImplemented 
let deleteUsersId _request =  
 failwith NotImplemented 
let putUsersId _request =  
 failwith NotImplemented 
let getUsersId _request =  
 failwith NotImplemented 
let postUsers _request =  
 failwith NotImplemented 
let getUsers _request =  
 failwith NotImplemented 
