(* Generated by generator.ml 2026-07-24T04:46:30Z *)

open Lwt.Infix

let login_handler next request =
  match Dream.session_field request "user" with
  | Some _ -> next request
  | None ->
      Dream.json
        ~code:401
        ~headers:[("Content-Type", "application/json")]
        "Unauthorized access"

let login_handler_admin next request =
  match Dream.session_field request "user" with
  | Some _ -> Helpers.checkPrems request (fun () -> next request)
  | None ->
      Dream.json
        ~code:401
        ~headers:[("Content-Type", "application/json")]
        "Unauthorized access"

let login_handler_judge next request =
  let open Redis_lwt in
  match Dream.session_field request "user" with
  | Some _ -> Helpers.checkPrems request (fun () ->
      Lwt_pool.use Db.pool (fun conn ->
          Client.hget conn ("user:" ^ Dream.session_id request) "role" )
      >>= function
      | Some role when Openapi.userRole_of_json role = Openapi.Judge ->
          next request
      | _ ->
          Dream.json
            ~code:403
            ~headers:[("Content-Type", "application/json")]
            "Forbidden - judge only" )
  | None ->
      Dream.json
        ~code:401
        ~headers:[("Content-Type", "application/json")]
        "Unauthorized access"

let () =
  let app =
    Dream.router
      [
        Dream.get "/" (fun _request ->
          Dream.html "/")
        (* Additional routes go here *)
;Dream.scope "/users" [login_handler] 
[
 Dream.get "" Users.getUsers;
 Dream.post "" Users.postUsers;
 Dream.get "/:id" Users.getUsersId;
 Dream.put "/:id" Users.putUsersId;
 Dream.delete "/:id" Users.deleteUsersId;
]
;Dream.scope "/auth" [] 
[
 Dream.post "/login" Auth.postAuthLogin;
 Dream.post "/register" Auth.postAuthRegister;
]
;Dream.scope "/problems" [login_handler] 
[
 Dream.get "/:id" Problems.getProblemsId;
 Dream.put "/:id" Problems.putProblemsId;
 Dream.delete "/:id" Problems.deleteProblemsId;
 Dream.get "/:id/testcases" Problems.getProblemsIdTestcases;
 Dream.post "/:id/testcases" Problems.postProblemsIdTestcases;
]
;Dream.scope "/submissions" [login_handler] 
[
 Dream.post "" Submissions.postSubmissions;
 Dream.get "/:id" Submissions.getSubmissionsId;
]
;Dream.scope "/judge" [login_handler_judge] 
[
 Dream.post "/next" Judge.postJudgeNext;
 Dream.post "/:submissionId/result" Judge.postJudgeSubmissionIdResult;
]
;Dream.scope "/contests" [login_handler] 
[
 Dream.get "" Contests.getContests;
 Dream.post "" Contests.postContests;
 Dream.get "/:id" Contests.getContestsId;
 Dream.put "/:id" Contests.putContestsId;
 Dream.delete "/:id" Contests.deleteContestsId;
 Dream.get "/:contestsId/problems" Contests.getContestsContestsIdProblems;
 Dream.post "/:contestsId/problems" Contests.postContestsContestsIdProblems;
 Dream.get "/:contestId/submissions" Contests.getContestsContestIdSubmissions;
 Dream.get "/:id/scoreboard" Contests.getContestsIdScoreboard;
]
;Dream.scope "/admin" [login_handler_admin] 
[
 Dream.get "/yodac/config" Admin.getAdminYodacConfig;
 Dream.put "/yodac/config" Admin.putAdminYodacConfig;
 Dream.get "/yodac/config/history" Admin.getAdminYodacConfigHistory;
]]
|> Dream.memory_sessions ~lifetime:(60.0 *. 60.0)
|> Dream.logger
in

Dream.run
  ~interface:"0.0.0.0"
  ~port:8001
  app
